### ISSUE TITLE
Send a list of movies on request

### ISSUE THREAD

**Issue by youmustgo** [MIC-TEAM/miccha-server#1]
## Summary

아래 API 를 구현해야 한다.
https://github.com/MIC-TEAM/miccha-design/issues/5#issuecomment-841773382

## To do
- [x] `R2DBC` 테스트 코드 작성하기
- [x] `Movie` 클래스 만들기
- [x] `MovieRepository` 클래스 만들기
- [x] `Config` 클래스 만들기

## Deadline

2021년 5월 21일

**Comment by youmustgo** [comment]
아래 항목을 확인하고 넘어가자:

- [ ] 테스트 클래스에서 `@AutoWired` 가 안 되는 부분
- [ ] `Statement.execute` 에 `flatMap` 을 사용할 수 없던 부분  
- [ ] `@Table` 이 필요한 이유
- [ ] 조인된 결과를 담는 클래스를 만드는 방법

**Comment by dhlee128** [comment]
#### ✔ 테스트 클래스에서 @AutoWired 가 안 되는 부분
1. xxx.yml파일에 (설정)정보를 계층구조로 적는다.
2. 사용할 필드에 @Value("${yml에서 지정한 키 값}")
3. 해당 클래스는 컨테이너가 빈으로 등록을 해줘야하니 컴포넌트 클래스(@Component,@Service,@Controller 등)을 붙인다.
4. 테스트 코드에서 주입받을 필드에 @Autowired 붙인다.(필드주입 방식)
-> 테스트 클래스에서 @SpringBootTest가 없으니 주입이 되지않았다. 해당 어노테이션의 기능은 테스트에 필요한 빈을 모두 생성해주며 @RunWith(SpringRunner.class)와 같이 사용해야한다.

#### ✔ `@Table` 이 필요한 이유
https://docs.spring.io/spring-data/r2dbc/docs/current/reference/html/#reference `참고` 16.4. Metadata-based Mapping
데이터베이스가 저장되는 테이블의 이름을 지정하여 해당 클래스가 테이블과 매핑되는 클래스임을 명시. 해당 어노테이션이 없어도 올바르게 매핑되지만 도메인 객체를 처음 저장할 때 속도가 약간 저하된다.

#### ✔
Repisitory -> ReactiveCrudRepository를 상속받는 인터페이스 구현 or @Repository 클래스 작성(DatabaseClient의 execute(), select()등 사용 가능)
https://brunch.co.kr/@springboot/178 `참고`
